# Generated by Django 5.2.7 on 2025-11-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total",
        ),
    ]
