# Generated by Django 5.2.7 on 2025-11-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="zipcode",
            field=models.FloatField(max_length=200),
        ),
    ]
