# Generated by Django 5.2.7 on 2025-11-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_order_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="zipcode",
            field=models.CharField(max_length=200),
        ),
    ]
