# Generated by Django 5.2.7 on 2025-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_order_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default="1", max_length=200),
            preserve_default=False,
        ),
    ]
